[package]
org = "testOrg"
name = "bal_type_processing"
version = "0.1.0"
distribution = "2201.9.2"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerinax"
name = "mi"
version = "0.1.3"
repository = "local"
